[build]
builder = "NIXPACKS"

[phases.build]
cmds = [
  "echo 'üè∞ Building Kingdom Server...'"
]

[start]
cmd = "cd /app/server && echo 'üè∞ Starting Kingdom of Minecraftia Server...' && echo 'ÔøΩ Server Configuration:' && echo '  Memory: ${MEMORY_MIN:-2G} - ${MEMORY_MAX:-4G}' && echo '  World: world' && echo '  Plugins: $(ls plugins/ | wc -l) installed' && echo '‚úÖ Kingdom server ready!' && exec java -Xms${MEMORY_MIN:-2G} -Xmx${MEMORY_MAX:-4G} -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar nogui"

[variables]
MEMORY_MIN = "2G"
MEMORY_MAX = "4G"
SERVER_NAME = "Kingdom of Minecraftia"
